config/routes.rb
Lf::Application.routes.draw do
  get "pages/info"
  resources :countdowns

  root :to => redirect('/countdowns')

end

app/models/countdown.rb
class Countdown < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  include InferredSlug::Slug
  
  validates :title, presence: true, length: { minimum:4 }
  validates_datetime :time, :after => :now
  
  def slug
    "#{id}-#{title}"
  end
  
  def to_param
    normalized_title = title.gsub(' ', '-').gsub(/[^a-zA-Z0-9\_\-\.]/, '')
    "#{self.id}-#{normalized_title}"
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/countdowns_controller.rb
class CountdownsController < ApplicationController
  before_action :set_countdown, only: [:show, :edit, :update, :destroy]

  # GET /countdowns
  # GET /countdowns.json
  def index
    @countdowns = Countdown.all
  end

  # GET /countdowns/1
  # GET /countdowns/1.json
  def show
  end

  # GET /countdowns/new
  def new
    @countdown = Countdown.new
  end

  # GET /countdowns/1/edit
  def edit
  end

  # POST /countdowns
  # POST /countdowns.json
  def create
    @countdown = Countdown.new(countdown_params)

    respond_to do |format|
      if @countdown.save
        format.html { redirect_to @countdown, notice: 'Countdown was successfully created.' }
        format.json { render action: 'show', status: :created, location: @countdown }
      else
        format.html { render action: 'new' }
        format.json { render json: @countdown.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countdowns/1
  # PATCH/PUT /countdowns/1.json
  def update
    respond_to do |format|
      if @countdown.update(countdown_params)
        format.html { redirect_to @countdown, notice: 'Countdown was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @countdown.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countdowns/1
  # DELETE /countdowns/1.json
  def destroy
    @countdown.destroy
    respond_to do |format|
      format.html { redirect_to countdowns_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_countdown
      @countdown = Countdown.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def countdown_params
      params.require(:countdown).permit(:title, :time, :image, :description, :link)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countdowns_helper.rb
module CountdownsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/countdowns/_form.html.erb
<%= form_for @countdown, :html => {:multipart => true, :class => 'form'} do |f| %>
  <% if @countdown.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@countdown.errors.count, "error") %> prohibited this countdown from being saved:</h2>

      <ul>
      <% @countdown.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time, order: [:day, :month, :year], :minute_step => 5, :class => 'dropdown-menu' %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit 'Start counting', :class => 'btn btn-success btn-lg' %>
  </div>
<% end %>

app/views/countdowns/edit.html.erb
<h1>Editing countdown</h1>

<%= render 'form' %>

<%= link_to 'Show', @countdown %> |
<%= link_to 'Back', countdowns_path %>

app/views/countdowns/index.html.erb
<h1>Listing countdowns</h1>

<%= link_to 'New Countdown', new_countdown_path, {:class => 'btn btn-success btn-lg'} %>

</br>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>Title</th>
      <th>Time</th>
      <th>Image</th>
      <th>Description</th>
      <th>Link</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @countdowns.each do |countdown| %>
      <tr>
        <td><%= countdown.title %></td>
        <td><%= link_to image_tag(countdown.image_url, :height => 30), countdown.image_url %></td>
		<td><%= countdown.time %></td>
        <td><%= countdown.description %></td>
        <td><%= countdown.link %></td>
        <td><%= link_to 'Show', countdown, :class => "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Edit', edit_countdown_path(countdown), :class => "btn btn-default btn-sm" %></td>
        <td><%= link_to 'Destroy', countdown, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/countdowns/new.html.erb
<h1>New countdown</h1>

<%= render 'form' %>

<%= link_to 'Back', countdowns_path %>

app/views/countdowns/show.html.erb
<p id="notice"><%= notice %></p>

<% content_for :pagetitle do %>
	<title><%= @countdown.title %> – We are lookingforward.to</title>
<% end %>

<% content_for :background do %>
	<style type="text/css" media="screen">
		.jumbotron {
  		background: url('<%= @countdown.image_url if @countdown.image? %>') no-repeat top center;
			background-size: 110% auto;
		}
	</style>
<% end %>

<% content_for :title do %>
	<%= @countdown.title %>
<% end %>

<% content_for :link do %>
	<% if @countdown.link? %>
		<%= link_to 'Details', @countdown.link, :class => 'btn btn-default btn-xs', 
						:style => 'margin-left: 15px; vertical-align: 40%; line-height: 1.5em' %>
	<% end %>
<% end %>

<% content_for :countdown do %>
  
	<script type='text/javascript'>
		
		var count = '<%= @countdown.time.to_i %>';
		var now = Math.round(new Date().getTime() / 1000);
		var days, hours, minutes, seconds,tmp;
		
		var timer = $.timer(
			function() {
				tmp = count-now;
				if(tmp <=0 ) {
					$('.count').html('<tr><th>This event is over.</th></tr>');
				}
				else {
					seconds = tmp % 60;
					if (seconds < 10) {
						seconds = '0'+seconds;
					}
					minutes = Math.floor(tmp/60) % 60;
					if (minutes < 10) {
						minutes = '0'+minutes;
					}
					hours 	= Math.floor(tmp/60/60) % 24;
					if (hours < 10) {
						hours = '0'+hours;
					}
					days		= Math.floor(tmp/60/60/24);
					if (days < 10) {
						days = '0'+days;
					}
					
					$('.count').html('<tr><th>'+days+'</th><th>:</th><th>'+hours+'</th><th>:</th><th>'+minutes+'</th><th>:</th><th>'+seconds+'</th></tr>');
				}
				count--;
			}, 1000, true
		);
    
  </script>
<% end %>

<p>
  <strong>Title:</strong>
  <%= @countdown.title %>
</p>

<p>
  <strong>Time:</strong>
  <%= @countdown.time %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@countdown.image_url, :width => 600) if @countdown.image.present? %>
</p>

<p>
  <strong>Description:</strong>
  <%= @countdown.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @countdown.link %>
</p>

<%= link_to 'Edit', edit_countdown_path(@countdown) %> |
<%= link_to 'Back', countdowns_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<%= yield :pagetitle %>
	<%= stylesheet_link_tag "application", :media => "all" %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	
	<%= yield :background %>
	
	<div class="jumbotron" id="jumbotron">
		<div class="container text-center">
			<!-- <%= yield %> -->
			
			<h1 class="text-center title"><strong><%= yield :title %></strong><%= yield :link %></h1>
			
			<%= yield :countdown %>
			
			<div id="countdown" class="text-center">
				<table border="0" id="countdown-table" class="table table-condensed table-nonfluid count">
										
				</table>
			</div>
			
			
			
			<!-- <div id="buttons">
				<%= yield :buttons %>
			</div> -->
			
		</div>
	</div>
	
	<div class="container">
		<%= yield %>
	</div>
	
	<div class="col-md-6 col-md-offset-3">
		<%= yield :countdown %>
	</div>
	
	<script src="http://code.jquery.com/jquery-latest.js"></script>
	
	<script type="text/javascript" charset="utf-8">
		var height = $(window).height(); 
		$("#jumbotron").height(height);
	</script>
	
</body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>